CREATE TABLE message (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	message varchar(255) not null,
	modification_time varbinary(255),
	created_date varbinary(255) not null,
	created_by_user varchar(255) not null,
	modified_by_user varchar(255),
);

create sequence message_sequence start with 1 increment by 1;
