/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.plilja.springplayground.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for HelloControllerApi
 */
@Ignore
public class HelloControllerApiTest {

    private final HelloControllerApi api = new HelloControllerApi();

    
    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexUsingDELETETest() {
        String response = api.indexUsingDELETE();

        // TODO: test validations
    }
    
    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexUsingGETTest() {
        String response = api.indexUsingGET();

        // TODO: test validations
    }
    
    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexUsingHEADTest() {
        String response = api.indexUsingHEAD();

        // TODO: test validations
    }
    
    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexUsingOPTIONSTest() {
        String response = api.indexUsingOPTIONS();

        // TODO: test validations
    }
    
    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexUsingPATCHTest() {
        String response = api.indexUsingPATCH();

        // TODO: test validations
    }
    
    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexUsingPOSTTest() {
        String response = api.indexUsingPOST();

        // TODO: test validations
    }
    
    /**
     * index
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexUsingPUTTest() {
        String response = api.indexUsingPUT();

        // TODO: test validations
    }
    
}
