/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package se.plilja.springplayground.client.api;

import se.plilja.springplayground.client.model.UserAuth;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserAuthControllerApi
 */
@Ignore
public class UserAuthControllerApiTest {

    private final UserAuthControllerApi api = new UserAuthControllerApi();

    
    /**
     * create
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUsingPOSTTest() {
        UserAuth message = null;
        UserAuth response = api.createUsingPOST(message);

        // TODO: test validations
    }
    
    /**
     * get
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUsingGETTest() {
        Long id = null;
        UserAuth response = api.getUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listUsingGETTest() {
        List<UserAuth> response = api.listUsingGET();

        // TODO: test validations
    }
    
}
